version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: always
  ui:
    build:
      context: ./
      dockerfile: docker/ui/Dockerfile
    ports:
      - "80:80"
    expose:
      - 80
    restart: always
    depends_on:
      - api